#!/bin/bash

# Telegram Bot Deployment Script for cPanel
# This script helps deploy the Telegram bot integration to production

echo "🚀 Telegram Bot Deployment Checklist"
echo "===================================="
echo ""

echo "📦 Files to upload to production server:"
echo ""
echo "1. routes/api.php (NEW FILE)"
echo "2. bootstrap/app.php (MODIFIED)"
echo "3. app/Http/Controllers/Api/TelegramWebhookController.php (MODIFIED)"
echo "4. app/Services/TelegramService.php"
echo "5. app/Http/Controllers/Admin/TelegramBroadcastController.php"
echo "6. app/Models/TelegramBroadcast.php"
echo "7. app/Jobs/SendTelegramBroadcast.php"
echo "8. resources/views/admin/telegram/ (all files)"
echo "9. database/migrations/2026_01_30_111826_add_telegram_fields_to_users_table.php"
echo "10. database/migrations/2026_01_30_111848_create_telegram_broadcasts_table.php"
echo ""

echo "⚙️ Commands to run on production server via SSH or cPanel Terminal:"
echo ""
echo "# 1. Navigate to your Laravel directory"
echo "cd /home/username/qattabor"
echo ""
echo "# 2. Add Telegram config to .env file"
echo "cat >> .env << 'EOF'"
echo ""
echo "# Telegram Bot Configuration"
echo "TELEGRAM_BOT_TOKEN=7884993170:AAFX-M-assMcELoJe1hV0sp3tH4PpvRNym4"
echo "TELEGRAM_BOT_USERNAME=@qattabor_bot"
echo "TELEGRAM_WEBHOOK_URL=https://qattabor.uz/api/telegram/webhook"
echo "TELEGRAM_ADMIN_CHAT_ID=849124681"
echo "EOF"
echo ""
echo "# 3. Run migrations"
echo "php artisan migrate --force"
echo ""
echo "# 4. Clear all caches"
echo "php artisan optimize:clear"
echo ""
echo "# 5. Cache for production"
echo "php artisan config:cache"
echo "php artisan route:cache"
echo "php artisan view:cache"
echo ""
echo "# 6. Test the webhook endpoint"
echo "curl https://qattabor.uz/api/telegram/webhook"
echo ""

echo "✅ After deployment, test:"
echo "1. Visit: https://qattabor.uz/api/telegram/webhook (should show JSON response)"
echo "2. Visit: https://qattabor.uz/admin/telegram (admin panel)"
echo "3. Set webhook in Telegram"
echo ""

echo "📱 Set Telegram Webhook:"
echo "Visit: https://qattabor.uz/admin/telegram/settings/webhook"
echo "Or run: curl -X POST \"https://api.telegram.org/bot7884993170:AAFX-M-assMcELoJe1hV0sp3tH4PpvRNym4/setWebhook?url=https://qattabor.uz/api/telegram/webhook\""
echo ""
